### ISSUE TITLE
How to turn off global BA and loop closure detection

### ISSUE THREAD

**Issue by C-H-Chien** [PeterFWS/Structure-PLP-SLAM#19]
Hi, I would like to evaluate your amazing work in a **visual odometry mode** by turning off the global bundle adjustment and the loop closure detection. The modules of BA, loop closure detection, etc are tightly coupled in the pipeline, so I wonder how this can be achieved in order to leave only the tracking module.
Thank you!

**Comment by PeterFWS** [comment]
Hi Chien,

you should be able to turn off the loop detection as indicated in the Pangolin GUI,
<img width="99" alt="image" src="https://github.com/PeterFWS/Structure-PLP-SLAM/assets/33999274/969cfed6-7e05-4a5f-b249-a47728c45e50">

or you can navigate to the code:
-> Structure-PLP-SLAM/src/pangolin_viewer/viewer.cc
change the code #58: **loop_detection_mode_(system->loop_detector_is_enabled())**
make the loop detection un-enabled.

In this way, the global BA is turned off, and no loop closure.

Best,

**Comment by C-H-Chien** [comment]
Hi @PeterFWS ! Thank you so much for your information. Glad to know that this is a simple step!
