### ISSUE TITLE
g2o version

### ISSUE THREAD

**Issue by whu-gr** [PeterFWS/Structure-PLP-SLAM#5]
Thanks for your great work! But there are some problems when compiling.
I have de-activated BUILD_WITH_MARCH NATIVE in cmake, but when I run "make -j4", the following error occurs:
` /PLPSLAM/optimize/g2o/se3/shot_vertex.h:58:42: error: ‘number_t’ does not name a type; did you mean ‘timer_t’?`
and some g2o errors, for example:
`error: ‘Matrix2’ in namespace ‘g2o’ does not name a type`
It seems to be a g2o version problem, Could you please offer your g2o version? Thanks a lot!

**Comment by PeterFWS** [comment]
hi,

you may try a version from late 2019 since the base-code OpenVSLAM was released in 2019, while the ORB-SLAM was released even earlier in 2017.

For example, the commit **fcba4eaca6f20d9a5792404cc8ef303aeb8ba5d2** of g2o, which was from 23.11.2019.

Best,
