### ISSUE TITLE
Map Viewer only show camera, did not show others 

### ISSUE THREAD

**Issue by RedRenXL** [PeterFWS/Structure-PLP-SLAM#8]
Hi,
I tried multiple datasets, the image viewer is available, it can detect features and lines, but the map viewer only shows the camera, the others do not

**Comment by RedRenXL** [comment]
I click the Follow Camera twice in Pangolin., and that have some effect

**Comment by PeterFWS** [comment]
Hi, 

I am not sure what caused this problem. No modification was made to the Pangolin and it is just used for visualization.

are you using the latest version of Ubuntu and Pangolin? I am not sure if there are compatibility issues.   Maybe you can try to install an older version of Pangolin and try again.

or could you try to run the original orb-slam and see if the same problem exists?

let me know if you found out something.

Best,

**Comment by RedRenXL** [comment]
Hi，
I used the latest Pangolin and tested orbslam without this problem, but in openVslam, it may be related to the version. Through testing I found the problem can be  solved by double-click the Follow Camera  in Pangolin。

**Comment by PeterFWS** [comment]
ok! good to know!

thanks for your testing.

**Comment by PeterFWS** [comment]
Hello,

thanks again for your testing. Recently, I configured a new gaming laptop with ubuntu 22.04 installed. After I successfully tested ORB-SLAM2 and Stella-SLAM (OpenVSLAM), I found out my system encountered same problem as yours. 

The basic visualization code is the same as OpenVSLAM, however I do not see the reason why the  map viewer does not show anything in the beginning, which can solved by double click "Follow Camera", but this is not optimal.

Not sure if you have any new findings, please let me know.

Best,
